sudo: required
cache:
  directories:
  # - texlive
before_install:
- |
  if [[ ! -e ./texlive/bin/x86_64-linux/tlmgr ]]; then
    wget http://mirrors.ctan.org/systems/texlive/Source/install-tl-unx.tar.gz -O - | tar -x --gzip
    mv $(ls | grep install) install-tl
    ./install-tl/install-tl -profile texlive.profile
  fi
- export PATH=$(pwd)/texlive/bin/x86_64-linux:$PATH
- apt-get install texlive-xetex
- tlmgr install $(cat .tlmgr-dep)
# see http://tex.stackexchange.com/questions/344821/cslatex-and-texlive
# show us what hyphen.cfg looks like
- cat /home/travis/build/ghseeli/grad-school-notes/texlive/texmf-dist/tex/cslatex/base/hyphen.cfg
- tlmgr update --self
- tlmgr update --all
script:
- mkdir _build
- cd Algebra
- pdflatex -output-directory ../_build master.tex
- cd ../Complex\ Analysis
- pdflatex -output-directory ../_build complex-analysis-notes.tex
- cd ../Differential\ Topology
- pdflatex -output-directory ../_build differential-topology-notes.tex
- cd ../Richards\ Algebra
- pdflatex -output-directory ../_build richards-algebra-book.tex
- cd ..

before_deploy:
- perl .rm-pdf-from-gitignore.pl
- mv _build/master.pdf _build/algebra.pdf
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GEZri02xptnKjM/kN8dw9XC+GyECSQEQQ1PwK+LPBqGh8MlCIHIu1mp8DvPW5sh9My0nUON6R/a6NLQOPcOr6DkBnb/hc0MWHEWd9awIUos1hlZLi/sNDv2WLVkREsAImmHQ3waojrhYQVDaT2PmcwZ1UYm3I847i5inVfQ1exLmh7r4mcWonpBuJvQi9oSvQheTFj+r8wPFyb6GjFgXjoS7HYOFnV8pTj8va1zZIOTlidqzBjiSo69UX4Oa4ihveNwFIsUZNfQvbvHAjFjDvtdP/UQ79rJx4jYO4Eb2hoBuIk6GAzou4KVc39tBlCD+bCo8jishbpc0QWS5ukZ4CeFjqd/oFrlwv9xfPzmnMRaP+gbQVJ+Xyx8i0wswAb7zWNRbR5XwxD6QImcOdOacWxLYOAgxjd/Lv96n3bCD20JHC9tm+zwsDjv2KxynSN/+tcXF4VdNQmbxIJuD5LUglu8YAtfKurXMoBY/QBFmvVvwX2/I/oQJQzgzHAleteZRFbQTz84IugcJdPXnXu+zYzbq+9c99Fpm3M1gtJeXfkVfEplROB0cHhpSqn+FhSyro+aKrOsSWxO85B+0n+HuMnI4Ua/tT2q521VFIKNalubYcsCY5WeVSBOyjTONO2DT7jOxMKId0HMsVCGP5+hiVZNnhlfxZN9G11VJvA9sym8=
  file:
  - _build/algebra.pdf
  - _build/complex-analysis-notes.pdf
  - _build/differential-topology-notes.pdf
  - _build/richards-algebra-book.pdf
  on:
    repo: ghseeli/grad-school-notes
    tags: true
