sudo: required

cache:
  directories:
    - texlive

before_install:
  # LaTeX package
  - |
    if [[ ! -e ./texlive/bin/x86_64-linux/tlmgr ]]; then
      wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz -O - | tar -x --gzip
      mv $(ls | grep install) install-tl
      ./install-tl/install-tl -profile texlive.profile
    fi
  - export PATH=$(pwd)/texlive/bin/x86_64-linux:$PATH
  - tlmgr install $(cat .tlmgr-dep)
  - tlmgr update --self
  - tlmgr update --all
script:
- mkdir _build
- cd Algebra
- pdflatex -output-directory ../_build master.tex
- cd ../Complex\ Analysis
- pdflatex -output-directory ../_build complex-analysis-notes.tex
- cd ../Differential\ Topology
- pdflatex -output-directory ../_build differential-topology-notes.tex
deploy:
  provider: releases
  file:
  - _build/master.pdf
  - _build/complex-analysis-notes.pdf
  - _build/differential-topology-notes.pdf
  skip_cleanup: true
  on:
    branch: master